typography_spectrum: 0.1543086797464639
color:
  brandStrength: 0.16627603746019304
  lightness: 0.981153029948473
  saturation: 0.0024072169326245785
  rhythmicContrast: 0.4631436977069825
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
opengraph:
  type: Karmic Images Facebook Page
  appId: facebook.com/karmic.images
layout_spectrum: 0.703779992647469
author:
  name: Charmaine Marchesi
  email: karmicimages.cm@gmail.com
name: Karmic Images
title: Welcome to Karmic Images
description: Specializing in Living Photography
