typography_spectrum: 0.35563366836868227
color:
  brandStrength: 0.07578757964074612
  lightness: 0.323738279286772
  saturation: 0.8812077504117042
  rhythmicContrast: 0.03613845817744732
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
opengraph:
  type: Karmic Images Facebook Page
  appId: facebook.com/karmic.images
layout_spectrum: 0.8107900351751596
author:
  name: Charmaine Marchesi
  email: karmicimages.cm@gmail.com
  url: karmicimages.com
name: Karmic Images
title: Welcome to Karmic Images
description: Specializing in Living Photography
